### ISSUE TITLE
problem deploying geofence 3.2.1 on tomcat 

### ISSUE THREAD

**Issue by kratosmat** [geoserver/geofence#87] opened 2017-03-02 10:13 UTC
Hi all,
I am trying to deploy geofence 3.2.1 on the same tomcat where is deployed geoserver 2.10, but it doesn't start properly with the following errors:
```
10:59:57,282  INFO LocalContainerEntityManagerFactoryBean:339 - Building JPA container EntityManagerFactory for persistence unit 'geofence'
10:59:57,555  INFO Version:37 - Hibernate Commons Annotations 3.2.0.Final
10:59:57,566  INFO Environment:593 - Hibernate 3.6.0.Final
10:59:57,585  INFO Environment:626 - hibernate.properties not found
10:59:57,613  INFO Environment:804 - Bytecode provider name : javassist
10:59:57,615  INFO Environment:685 - using JDK 1.4 java.sql.Timestamp handling
10:59:57,782  INFO Version:42 - Hibernate EntityManager 3.6.0.Final
10:59:57,839  INFO Ejb3Configuration:519 - Processing PersistenceUnitInfo [
	name: geofence
	...]
10:59:58,066  WARN XmlWebApplicationContext:546 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'geofenceEntityManagerFactory' defined in URL [jar:file:/usr/local/tomcat/webapps/geofence/WEB-INF/lib/geofence-persistence-3.2.1.jar!/applicationContext-geofenceDatasource.xml]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: javax.persistence.spi.PersistenceUnitInfo.getSharedCacheMode()Ljavax/persistence/SharedCacheMode;
10:59:58,068 ERROR ContextLoader:351 - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'geofenceEntityManagerFactory' defined in URL [jar:file:/usr/local/tomcat/webapps/geofence/WEB-INF/lib/geofence-persistence-3.2.1.jar!/applicationContext-geofenceDatasource.xml]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: javax.persistence.spi.PersistenceUnitInfo.getSharedCacheMode()Ljavax/persistence/SharedCacheMode;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1054) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:829) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326) [spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107) [spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727) [catalina.jar:8.5.11]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189) [catalina.jar:8.5.11]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.5.11]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752) [catalina.jar:8.5.11]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728) [catalina.jar:8.5.11]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734) [catalina.jar:8.5.11]
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952) [catalina.jar:8.5.11]
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823) [catalina.jar:8.5.11]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NoSuchMethodError: javax.persistence.spi.PersistenceUnitInfo.getSharedCacheMode()Ljavax/persistence/SharedCacheMode;
	at org.hibernate.ejb.Ejb3Configuration.configure(Ejb3Configuration.java:636) ~[hibernate-entitymanager-3.6.0.Final.jar:3.6.0.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateEjbPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateEjbPersistenceProvider.java:50) ~[spring-orm-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343) ~[spring-orm-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:319) ~[spring-orm-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	... 25 more
02-Mar-2017 10:59:58.481 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
02-Mar-2017 10:59:58.481 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/geofence] startup failed due to previous errors
```

**Comment by kratosmat** [comment] 2017-03-02 11:43
I solved by myself by adding a new exclusion in the service-impl pom.xml.

<exclusion>
                    <groupId>javax.persistence</groupId>
                    <artifactId>persistence-api</artifactId>
                </exclusion>

**Comment by mirandadam** [comment] 2017-03-22 11:56
Hi @kratosmat, I am having the same problem here. What exactly did you do to fix the issue?
Did you change pom.xml in the deployed application in the tomcat folder or did you have to rebuild geofence?
What lines did you add to the file?

**Comment by etj** [comment] 2017-03-22 14:47
The service modules use this dep management lines:

- https://github.com/geoserver/geofence/blob/v3.2.1/src/services/pom.xml#L608-L625

so the JPA1 lib is correctly *not* included in the build, but the webapp modules use a different dep management block which uses obsolete libs and does not perform the needed exclusion:

-  https://github.com/geoserver/geofence/blob/v3.2.1/src/gui/pom.xml#L574-L593

Going to fix the pom file and create a 3.2.2 release.

@mirandadam if you already deployed GeoFence, you can simply remove the file ``WEB-INF/lib/persistence-api-1.0.jar`` and restart the webapp.

**Comment by etj** [comment] 2017-03-22 17:49
Since this error could lead to a race condition preventing GeoFence to boot, a new [release 3.2.2](http://ares.boundlessgeo.com/geofence/3.2.x/release-v3.2.2-geofence-war.zip)  has been built.
Thanks for reporting @kratosmat @mirandadam.

**Comment by mirandadam** [comment] 2017-03-22 17:52
@etj, thanks!!!

**Comment by mirandadam** [comment] 2017-03-22 21:38
@etj, I have just tested the new release and can confirm that it works.

**Comment by jometho** [comment] 2017-08-04 09:43
Hi @mirandadam I'm having this same problem while deploying geofence.war (release-v3.3.0) on tomcat. Any help please:
----------------Log----------------------
12:36:49,853  WARN XmlWebApplicationContext:546 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'startupService' defined in class path resource [applicationContext-Service.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Cannot open connection
12:36:49,855  INFO LocalContainerEntityManagerFactoryBean:481 - Closing JPA EntityManagerFactory for persistence unit 'geofence'
12:36:49,868 ERROR ContextLoader:351 - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'startupService' defined in class path resource [applicationContext-Service.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Cannot open connection
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Cannot open connection
        at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1214)
        at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1147)
        at org.hibernate.ejb.QueryImpl.getSingleResult(QueryImpl.java:307)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:368)
        at com.sun.proxy.$Proxy121.getSingleResult(Unknown Source)
        at com.googlecode.genericdao.search.jpa.JPASearchProcessor.count(JPASearchProcessor.java:116)
        at com.googlecode.genericdao.dao.jpa.JPABaseDAO._count(JPABaseDAO.java:354)
        at com.googlecode.genericdao.dao.jpa.GenericDAOImpl.count(GenericDAOImpl.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
        at com.sun.proxy.$Proxy116.count(Unknown Source)
        at org.geoserver.geofence.services.GFUserAdminServiceImpl.getCount(GFUserAdminServiceImpl.java:120)
        at org.geoserver.geofence.gui.server.service.impl.StartupService.afterPropertiesSet(StartupService.java:47)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
        ... 25 more
Caused by: org.hibernate.exception.GenericJDBCException: Cannot open connection
        at org.hibernate.exception.SQLStateConverter.handledNonSpecificException(SQLStateConverter.java:140)
        at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:128)
        at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
        at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:52)
        at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:449)
        at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:167)
        at org.hibernate.jdbc.AbstractBatcher.prepareQueryStatement(AbstractBatcher.java:161)
        at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1700)
        at org.hibernate.loader.Loader.doQuery(Loader.java:801)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:274)
        at org.hibernate.loader.Loader.doList(Loader.java:2533)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2276)
        at org.hibernate.loader.Loader.list(Loader.java:2271)
        at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:452)
        at org.hibernate.hql.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:363)
        at org.hibernate.engine.query.HQLQueryPlan.performList(HQLQueryPlan.java:196)
        at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1268)
        at org.hibernate.impl.QueryImpl.list(QueryImpl.java:102)
        at org.hibernate.ejb.QueryImpl.getSingleResult(QueryImpl.java:274)
        ... 45 more
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Error while creating file "/geofence_db" [90062-176])
        at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1225)
        at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
        at org.hibernate.ejb.connection.InjectedDataSourceConnectionProvider.getConnection(InjectedDataSourceConnectionProvider.java:71)
        at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:446)
        ... 59 more
Caused by: org.h2.jdbc.JdbcSQLException: Error while creating file "/geofence_db" [90062-176]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
        at org.h2.message.DbException.get(DbException.java:178)
        at org.h2.message.DbException.get(DbException.java:154)
        at org.h2.store.fs.FilePathDisk.createDirectory(FilePathDisk.java:264)
        at org.h2.store.fs.FileUtils.createDirectory(FileUtils.java:43)
        at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:298)
        at org.h2.store.FileLock.lockFile(FileLock.java:346)
        at org.h2.store.FileLock.lock(FileLock.java:136)
        at org.h2.engine.Database.open(Database.java:622)
        at org.h2.engine.Database.openDatabase(Database.java:260)
        at org.h2.engine.Database.<init>(Database.java:254)
        at org.h2.engine.Engine.openSession(Engine.java:57)
        at org.h2.engine.Engine.openSession(Engine.java:164)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:142)
        at org.h2.engine.Engine.createSession(Engine.java:125)
        at org.h2.engine.Engine.createSession(Engine.java:27)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:331)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
        at org.h2.Driver.connect(Driver.java:74)
        at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
        at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
        at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1247)
        at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1221)
        ... 62 more
04-Aug-2017 12:36:49.872 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
04-Aug-2017 12:36:49.873 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/geofence] startup failed due to previous errors
---------------end----------------------

**Comment by nmco** [comment] 2017-08-04 10:36
@jometho you have a different issue:
```
Caused by: org.h2.jdbc.JdbcSQLException: Error while creating file "/geofence_db" [90062-176]
```
H2 is trying to create the file with path ``/geofence_db`` and is probably lacking permissions to do it. Did you change the original path location ?

**Comment by jometho** [comment] 2017-08-04 11:24
@nmco I haven't changed the original path. basically I'm using the default configurations.

This error occurs during installation; i.e. after I just copied geofence.war into _/tomcat/webapps_ then restarted tomcat.
I have made sure it geofence.war and geofence webapp has the same permissions as geoserver.war and geoserver webapp
I can't get geofence in the browser so I checked the logs and I found the error.

I have switched between different versions, v3.3.0, v3.2.2

Anything I'm missing?

**Comment by etj** [comment] 2017-08-08 08:53
@jometho the H2 file is created by default in the user's current directory.
You may want either do a `cd` to a writable location before starting tomcat, or set a specific path in your filesystem for the database files: in order to do that, use the `-Dgeofence-ovr=file:/PATH/TO/OVR/FILE.properties` property (as reported [here](https://github.com/geoserver/geofence/wiki/GeoFence-configuration#providing-a-configuration-file)) and create the property file containing the line:
```
geofenceDataSource.url=jdbc:h2:/ABSOLUTE/DIRECTORY/PATH/FILENAME_TEMPLATE
```
as reported in [the h2 configuration paragraph](https://github.com/geoserver/geofence/wiki/GeoFence-configuration#h2-configuration).

**Comment by mmft1359** [comment] 2020-03-15 19:45
@etj, thanks!!!

**Comment by drumbsd** [comment] 2021-07-15 09:08
Hello @etj, file persistence-api-1.0.jar seems still present in the latest nightly build 3.5.x and prevent this version to properly working. I'm using Tomcat 8.

**Comment by bhoefling-c2c** [comment] 2021-07-15 09:53
Noticed this also right now in a selfmade `v3.4.8` Geofence. Removing the `persistence-api*.jar` fixed it, Geofence starts up now.

**Comment by etj** [comment] 2021-07-15 10:06
Needed some investigation, seems a regression.

**Closed** 2023-11-09 13:26 UTC
Labels: bug
