### ISSUE TITLE
Path problem when using embedded module on a path with spaces on Windos

### ISSUE THREAD

**Issue by yong2khoo88** [geoserver/geofence#76] opened 2016-05-06 01:47 UTC
I am using Windows.
I use embedded module in the geoserver, v2.8.3
But when i restart the geoserver, there is an error:
`Error while creating file C:\Program Files (x86)\GeoServer 2.8.3\bin\Program Files (x86)GeoServer 2.8.3data_dir\geofence\geofence_db [90062-119]`

Is the error message correctly displayed or is the path installation having some problem there?

Thanks in advance.

![geofence-path](https://cloud.githubusercontent.com/assets/5007089/15062122/95cd94e8-136f-11e6-9d97-aa7fcb39aa97.jpg)

**Comment by yong2khoo88** [comment] 2016-05-06 05:59
It turns out, the directory has to be granted the permission.
However, now, i can confirm that this is the path issue, which results in the consequence as attached:

![geofence-path2](https://cloud.githubusercontent.com/assets/5007089/15065430/1ccd2932-1392-11e6-8782-d39c3ba20c7a.jpg)


the geofence_db is created inside the directory bin, which is strange.

ALSO, IT CAUSES THE GEOSERVER ERROR: 'COULD NOT FIND LAYER'! (sorry, it took me hours to realize it is caused by 'copy and paste' the jars file from geofence)

i am not sure if it is caused by the data_dir/security folder as stated in the link [here](http://gis.stackexchange.com/questions/20726/intermittent-could-not-find-layer-and-bad-request-errors-on-geoserver?newreg=806f5cdd11a34912aab143dfad6826ed). The reason is i am unable to solve the issue by editing something in the data_dir/security folder.

Would appreciate if help is provided on this.

Thanks.

**Comment by yong2khoo88** [comment] 2016-05-06 06:26
To clarify, what i want to do, is to use GeoFence as an authentication/authorization layer for my web service. However, when copy and paste the jar file into the directory (and before i do anything), it causes the error 'Could not find layer' when i try reload the map and the raster layer again. That makes me suspect that the installation must be something wrong.

Hope this is clear enough.

**Comment by simboss** [comment] 2016-05-06 08:46
Thx for the report, I will prioritize this one.

It might be related to having spaces in the path (wild guess) but not sure.

**Comment by yong2khoo88** [comment] 2016-05-06 09:10
Thanks for your acknowledgement. Look forward to hearing from you soon.

**Comment by nmco** [comment] 2016-05-06 13:32
Hi,
two things are happening here:

-  if geoserver data directory path contains spaces, geofence will put the geofence directory in tomcat bin directory (this only happens on windows) but geofence will work normally (this behavior will be fixed)
- geofence by default "hide" all layers, which is probably making the "layer not found error" appears in this case (this is the expected behavior) you need to define a rule that allows the layer to be requested

Defining a rule that allows all layers to be requested by everyone:
![geofenc_allow_rule](https://cloud.githubusercontent.com/assets/1590542/15074479/2ef3a000-1397-11e6-880e-6f016aab78b8.png)


Don't forget to invalidate the cache if needed:
![geofenc invalidate](https://cloud.githubusercontent.com/assets/1590542/15074483/3ae22cc4-1397-11e6-8fc4-2333508fe36d.png)

**Comment by simboss** [comment] 2016-05-06 15:10
I am going to reword this issue as the problem seems to be related to handling path on windows mainly.

**Comment by yong2khoo88** [comment] 2016-05-07 02:24
Thank you for the quick and helpful response!
I would come back to this on the coming Monday and update you again.

**Comment by yong2khoo88** [comment] 2016-05-09 02:26
Hi simboss,
Thanks again for your clarification on the observations.
Now the error message of "layer not found error" disappears. Instead, it says "Full authentication is required to access this resource".

Is that I should add something on the client side to be able to request it?

**Comment by simboss** [comment] 2016-05-09 07:48
We need to bring this discussion to the mailing list, I am going to close this issue.

**Closed by simboss** 2016-05-09 07:48 UTC
Labels: bug, Priority: Blocker, Windows
