### ISSUE TITLE
2.2x Build Error

### ISSUE THREAD

**Issue by biomap** [geoserver/geofence#48] opened 2015-05-18 01:03 UTC
```
[ERROR] BUILD ERROR
[INFO] ---------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

Project ID: it.geosolutions.geogwt.widgets.map:mappanel

Reason: Error getting POM for 'it.geosolutions.geogwt.widgets.map:mappanel' from the repository: Unable to read local copy of metadata: Cannot read metadata from '/root/.m2/repository/it/geosolutions/geogwt/widgets/map/mappanel/0.2-SNAPSHOT/maven-metadata-sonatype-nexus-releases.xml': end tag name </body> must match start tag name < hr > from line 5 (position: TEXT seen ...</center>\r\n</body>... @6:8) it.geosolutions.geogwt.widgets.map:mappanel:pom:0.2-SNAPSHOT for project it.geosolutions.geogwt.widgets.map:mappanel.
```

```
Build env: mvn -version
Apache Maven 2.2.1 (r801777; 2009-08-06 14:16:01-0500)
Java version: 1.7.0_79
Java home: /opt/oraclejdk7/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux" version: "3.10.0-229.4.2.el7.x86_64" arch: "amd64" Family: "unix"
```

I can confirm the tag is missing and have tried to insert the missing /hr tag however it seems that it is pulling a new one down from GS each time it builds.

On another note I cant get either 2.2x or 3.0 pre-built .war's to load from the on CentOS x64.  I had them running on 32bit system (after many restarts) but it seems very unstable still.

**Comment by aaime** [comment] 2015-05-18 06:01
We have it in production on a few sites, so very unstable it's certainly not. Can you describe the issues you had in deploy?

**Comment by biomap** [comment] 2015-05-18 06:31
My apologies for the characterization of very unstable,  just my frustration I suppose.  Tomcat seems to just hang and doesn't want to load geofence when the war is deployed.  It will run the processor up to over 60% (I have tried with various cores) it also takes all of the avail memory given to tomcat and will not start.  At this point Tomcat will timeout and has to be restarted to get to the manager.  I have tested on tomcat 7 and 8 and am using oracle jdk 7 (should I try another jdk?).  I have tested on win7 x64, cent 6 x64 and cent7 (only x64).  I have managed to start it on a test machine and had it setup.  It worked very well but deploying it to my production server fails and my test server here fail as well.   I plan on working with the REST API's and get a working dashboard so I am keen on getting this up and going.  I am happy to test and help out if I can be of assistance.   Thanks!

**Comment by etj** [comment] 2015-05-18 08:45
There is a jenkins job checking that geofence can be built without errors: 
   http://ares.boundlessgeo.com/jenkins/view/geofence/

Try using a later version of maven (3.0.5 or 3.1.1 should work). I guess the problem may be caused by how maven2 deals with HTTP 304 codes. maven xml files should not contain ```</center>\r\n</body>``` elements as reported in the error you encountered.

So:
1) upgrade your maven
2) remove the local files in ```/root/.m2/repository/it/geosolutions/geogwt```
3) build geofence again

You may also try a precompiled ```.war``` at http://ares.boundlessgeo.com/geofence/2.2.x/

**Comment by biomap** [comment] 2015-05-18 09:58
Thanks I will try maven 3.  I assumed geofence required maven 2 as is the case with geoserver (from what I have read).  

That is the war I have been using which I cant get it to load as mentioned above.  It will deploy and creates the geofence folder but not  geofence_db (h2 db) and does not start.

Where is the default build location for the h2 db and could it be a permission issue with creating it?

FAIL - Application at context path /geofence could not be started

Thanks

**Comment by aaime** [comment] 2015-05-18 12:02
GeoServer requires maven 3 too. Where did you read it needs maven 2?

**Comment by biomap** [comment] 2015-05-18 17:32
Thanks Andre I will revise and try again.  I must have read it somewhere else besides an official geoserver repo.  I will attempt again.

**Comment by biomap** [comment] 2015-05-18 21:05
I am building from an IDE now with mvn 3, however it is failing on the following dependencies. Appears all the links are down for hibernate-spatial. 

[INFO] GeoFence - GUI - Map plugin ....................... SUCCESS [1:11.066s]
[INFO] GeoFence - GUI - Web .............................. FAILURE [16.750s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18:49.654s
[INFO] Finished at: Mon May 18 14:47:46 CDT 2015
[INFO] Final Memory: 47M/221M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project geofence-gui-web: Could not resolve dependencies for project org.geoserver.geofence:geofence-gui-web:war:2.2.1-SNAPSHOT: Failure to find org.hibernatespatial:hibernate-spatial:jar:1.1.1 in http://maven.geo-solutions.it was cached in the local repository, resolution will not be reattempted until the update interval of geosolutions has elapsed or updates are forced -> [Help 1]
-----------------------------------

:(

**Comment by biomap** [comment] 2015-05-19 05:45
I have done more testing and it seems to just be isolated to Centos 7(from the OS's I have tried) in which it does not want to load on.  Sorry to cry wolf.  You may want to test against it in case I am wrong but i have geofence running on a variety of different machines now with the same config except for my CentOS7 servers which it will not load.  

Thanks!

**Comment by etj** [comment] 2015-05-27 13:20
Seems related to the platform security policy and not to geofence. Closing.

**Closed by etj** 2015-05-27 13:20 UTC
