### ISSUE TITLE
database structure change when application is running

### ISSUE THREAD

**Issue by cesarhein** [geoserver/geofence#54] opened 2015-08-28 18:44 UTC
I installed Geofence and I also configured Postgres + Postgis. Then I created database running these scripts:

 - geofence/doc/setup/sql/001_setup_db.sql
 - geofence/doc/setup/sql/002_create_schema_postgres.sql

But owing to norms into my organization, application users cant get priviledges to create or alter tables, they just can insert, update or delete records. Then I get an error when I try to add a new Rule in Geofence, when I check the log file I found that a column is missing (ip_high).

I installed Geofence locally in an other Postgres DB, and created a user with grant privileges, then I found that this DB is not the same as DB created with scripts above. Now a column called "catalog_mode" was added in tables gf_layer_details and gf_rule_limit; also three columns (ip_high, ip_low, and ip_size) was added to gr_rule table.

The question is... Can I solve the problem making a dump of the "new complete" schema in the production DB and trust that no other change is comming? Or I need mandatorily an application user with grant privileges in production environment?

An other question... Why the aplication need to change the DB structure?

Thanks a lot!

**Comment by etj** [comment] 2015-09-01 09:06
The sql scripts are a bit outdated indeed. They were in fact used to provide a way to create the db schema when the db user assigned to run geofence had no schema change privs, exactly as in your scenario.

The application shall change the DB structure *only on the first run*, in order to have hibernate create the DB schema; then the config files should be edited in order to have hibernate only validate the schema, with no further schema changes.

This means that tou can safely create a db schema locally, and then export the schema ddl to the production DB.

**Comment by etj** [comment] 2015-09-01 09:09
Also see #22

**Comment by etj** [comment] 2016-04-18 08:44
Can be seen as a duplicate of #22

**Closed by etj** 2016-04-18 08:44 UTC
